#ifndef _supported_boards_h_
#define _supported_boards_h_

// Board families
enum {
	BOARD_FAMILY_ARDUINO,
};

// Arduino boards
enum {
	BOARD_ARDUINO_UNO,
	BOARD_ARDUINO_LEONARDO,
	BOARD_ARDUINO_DUE,
	BOARD_ARDUINO_YUN,
	BOARD_ARDUINO_TRE,
	BOARD_ARDUINO_ZERO,
	BOARD_ARDUINO_MICRO,
	BOARD_ARDUINO_ESPLORA,
	BOARD_ARDUINO_MEGA_ADK,
	BOARD_ARDUINO_MEGA_2560,
	BOARD_ARDUINO_ETHERNET,
	BOARD_ARDUINO_ROBOT,
	BOARD_ARDUINO_MINI,
	BOARD_ARDUINO_NANO,
	BOARD_ARDUINO_LILYPAD,
	BOARD_ARDUINO_LILYPAD_SIMPLE,
	BOARD_ARDUINO_LILYPAD_SIMPLE_SNAP,
	BOARD_ARDUINO_LILYPAD_USB,
	BOARD_ARDUINO_PRO,
	BOARD_ARDUINO_PRO_MINI,
	BOARD_ARDUINO_FIO,
};

#endif // _supported_boards_h_
